### ISSUE TITLE
你家退订就一个HTML？

### ISSUE THREAD

**Issue by Mabbs** [yaonphy/Attitude#1]
# **做个人行不？别发垃圾邮件了！**

**Comment by yaonphy** [comment]
> 做个人行不？别发垃圾邮件了！

给你带来了不好的体验，非常抱歉。所有功能都是我一个人开发的，时间有点紧，有的邮件客户端会屏蔽邮件里的JS，所以退订这块还是不太完善，会尽快完善。没有太多的背景、资源去花钱推广，也是真心站在用户角度来做产品，希望谅解。肯定不会频繁推邮，邮件内容也不会那么营销化，邮件厂商这边也有信用评级，信誉太差会拉黑禁发的。
